<a href="https://colab.research.google.com/github/archita40/Neural-Network-Assignment-2/blob/main/NN_Project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2. Take a dataset from Kaggle and perform preprocessing using ANN and CNN concept?

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

%matplotlib inline
plt.style.use('fivethirtyeight')

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.1f}'.format)

In [4]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nelgiriyewithana/top-spotify-songs-2023")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/nelgiriyewithana/top-spotify-songs-2023/1.archive...

100%|██████████| 47.1k/47.1k [00:00<00:00, 1.78MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/nelgiriyewithana/top-spotify-songs-2023/versions/1

In [7]:
filepath = os.path.join(path, 'spotify-2023.csv')
spotify_df = pd.read_csv(filepath, encoding='latin-1')
display(spotify_df.head())

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,263,45,10,826,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,126,58,14,382,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,207,91,14,949,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,207,125,12,548,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,133,87,15,425,144,A,Minor,65,23,80,14,63,11,6

In [11]:
# Check missing values
print("Missing values before filling/dropping:")
display(spotify_df.isnull().sum())

if spotify_df['streams'].isnull().any():
    spotify_df['streams'].fillna(spotify_df['streams'].mean(), inplace=True)
    print("Missing 'streams' values filled with mean.")


if 'artist(s)_name' in spotify_df.columns:
    pass

display(spotify_df.head())

Missing values before filling/dropping:

track_name               0
artist(s)_name           0
artist_count             0
released_year            0
released_month           0
released_day             0
in_spotify_playlists     0
in_spotify_charts        0
streams                  0
in_apple_playlists       0
in_apple_charts          0
in_deezer_playlists      0
in_deezer_charts         0
in_shazam_charts        50
bpm                      0
key                     95
mode                     0
danceability_%           0
valence_%                0
energy_%                 0
acousticness_%           0
instrumentalness_%       0
liveness_%               0
speechiness_%            0
dtype: int64

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,263,45,10,826,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,126,58,14,382,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,207,91,14,949,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,207,125,12,548,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,133,87,15,425,144,A,Minor,65,23,80,14,63,11,6

In [15]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Initialize the StandardScaler
scaler = StandardScaler()

numerical_cols = [
    'artist_count', 'released_year', 'released_month', 'released_day',
    'in_spotify_playlists', 'in_spotify_charts', 'streams',
    'in_apple_playlists', 'in_apple_charts',
    'in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts',
    'bpm', 'danceability_%', 'valence_%', 'energy_%',
    'acousticness_%', 'instrumentalness_%', 'liveness_%', 'speechiness_%'
]

# Explicitly convert numerical columns to numeric, coercing errors to NaN
# This step is crucial if some 'numerical' columns might contain non-numeric strings.
for col in numerical_cols:
    # Check if the column is in the dataframe to avoid KeyError
    if col in spotify_df.columns:
        # Convert to numeric, setting errors to NaN
        spotify_df[col] = pd.to_numeric(spotify_df[col], errors='coerce')

# Handle missing values in numerical_cols before scaling, for example by filling with the mean
for col in numerical_cols:
    if col in spotify_df.columns and spotify_df[col].dtype in ['int64', 'float64']:
        spotify_df[col].fillna(spotify_df[col].mean(), inplace=True)

# Filter numerical_cols to only include those that are actually numeric after conversion
actual_numerical_cols = [col for col in numerical_cols if col in spotify_df.columns and np.issubdtype(spotify_df[col].dtype, np.number)]

spotify_df[actual_numerical_cols] = scaler.fit_transform(spotify_df[actual_numerical_cols])

print("Selected numerical features have been scaled using StandardScaler.")
display(spotify_df.head())
display(spotify_df.info())

Selected numerical features have been scaled using StandardScaler.

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",0.5,0.4,0.3,0.0,-0.6,6.9,-0.7,-0.3,4.2,-0.4,1.2,6.3,0.1,B,Major,0.9,1.6,1.1,0.2,-0.2,-0.7,-0.6
1,LALA,Myke Towers,-0.6,0.4,-0.9,1.0,-0.5,1.8,-0.7,-0.2,1.5,-0.3,1.9,2.7,-1.1,C#,Major,0.3,0.4,0.6,-0.8,-0.2,-0.6,-0.6
2,vampire,Olivia Rodrigo,-0.6,0.4,-0.0,1.7,-0.5,5.2,-0.7,0.3,3.1,-0.1,1.9,7.3,0.6,F,Major,-1.1,-0.8,-0.7,-0.4,-0.2,0.9,-0.4
3,Cruel Summer,Taylor Swift,-0.6,0.1,0.6,1.0,0.3,4.5,0.5,0.6,3.1,0.1,1.5,4.1,1.7,A,Major,-0.8,0.3,0.5,-0.6,-0.2,-0.5,0.5
4,WHERE SHE GOES,Bad Bunny,-0.6,0.4,-0.3,0.4,-0.3,1.9,-0.4,0.2,1.6,-0.1,2.0,3.0,0.8,A,Minor,-0.1,-1.2,1.0,-0.5,7.3,-0.5,-0.4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    float64
 3   released_year         953 non-null    float64
 4   released_month        953 non-null    float64
 5   released_day          953 non-null    float64
 6   in_spotify_playlists  953 non-null    float64
 7   in_spotify_charts     953 non-null    float64
 8   streams               953 non-null    float64
 9   in_apple_playlists    953 non-null    float64
 10  in_apple_charts       953 non-null    float64
 11  in_deezer_playlists   953 non-null    float64
 12  in_deezer_charts      953 non-null    float64
 13  in_shazam_charts      953 non-null    float64
 14  bpm                   953 non-null    float64
 15  key                   858 non-null    object
 16  mode                  953 non-null    object
 17  danceability_%        953 non-null    float64
 18  valence_%             953 non-null    float64
 19  energy_%              953 non-null    float64
 20  acousticness_%        953 non-null    float64
 21  instrumentalness_%    953 non-null    float64
 22  liveness_%            953 non-null    float64
 23  speechiness_%         953 non-null    float64
dtypes: float64(20), object(4)
memory usage: 178.8+ KB

None

In [17]:
from sklearn.model_selection import train_test_split

y = spotify_df['streams']  # 'streams' as the target variable
X = spotify_df.drop('streams', axis=1)  # Use all other columns as features

features_numerical_cols = [col for col in actual_numerical_cols if col != 'streams']

X = X[features_numerical_cols]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Data split into training and testing sets successfully.")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

Data split into training and testing sets successfully.
X_train shape: (762, 19)
X_test shape: (191, 19)
y_train shape: (762,)
y_test shape: (191,)

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Define the ANN model
model = Sequential([
    Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(8, activation='relu'),
    Dense(1, activation='linear')
])

print("ANN model defined successfully.")
model.summary()

ANN model defined successfully.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 465 (1.82 KB)

 Trainable params: 465 (1.82 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.compile(
    optimizer='adam',
    loss='mean_squared_error',
    metrics=['mean_absolute_error']
)

In [21]:
model.fit(X_train, y_train, epochs=20, batch_size=32)

Epoch 1/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 1.2559 - mean_absolute_error: 0.8143
Epoch 2/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0433 - mean_absolute_error: 0.7295
Epoch 3/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.9296 - mean_absolute_error: 0.6777
Epoch 4/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8430 - mean_absolute_error: 0.6402
Epoch 5/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7550 - mean_absolute_error: 0.6041
Epoch 6/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6560 - mean_absolute_error: 0.5671
Epoch 7/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5546 - mean_absolute_error: 0.5285
Epoch 8/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4759 - mean_absolute_error: 0.4905
Epoch 9/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4037 - mean_absolute_error: 0.4520
Epoch 10/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3581 - mean_absolute_error: 0.4189
Epoch 11/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3224 - mean_absolute_error: 0.3956
Epoch 12/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2984 - mean_absolute_error: 0.3765
Epoch 13/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2813 - mean_absolute_error: 0.3660
Epoch 14/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2654 - mean_absolute_error: 0.3526
Epoch 15/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2527 - mean_absolute_error: 0.3435
Epoch 16/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2416 - mean_absolute_error: 0.3346
Epoch 17/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2334 - mean_absolute_error: 0.3282
Epoch 18/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2273 - mean_absolute_error: 0.3225
Epoch 19/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2189 - mean_absolute_error: 0.3148
Epoch 20/20
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2121 - mean_absolute_error: 0.3090

In [22]:
loss, mae = model.evaluate(X_test, y_test)
print("Loss:", loss)
print("Mean Absolute Error:", mae)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2500 - mean_absolute_error: 0.3587
Loss: 0.2500256896018982
Mean Absolute Error: 0.3586837947368622